[package]
name = "hwtemp-rs"
version = "0.1.0"
authors = ["The Doctor", "thedoctor095@yahoo.com"]
edition = "2024"
readme = "README.md"
repository = "https://github.com/thedoctor095/hwtemp-rs"
license-file = "LICENSE"

[dependencies]
glob = "0.3.2"
